version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - '${PORT_BE}:80' # Export PORT for development
    environment:
      - DB_URI=mongodb://mongodb:27017/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - oakshort

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
      - '${PORT_FE}:80' # Export PORT for development
    environment:
      - API_URL=http://backend
    depends_on:
      - backend
    networks:
      - oakshort

  mongodb:
    image: mongo:6
    ports:
      - '${PORT_DB}:27017' # Export PORT for development
    volumes:
      - mongo-data:/data/db
    networks:
      - oakshort

networks:
  oakshort:
    driver: bridge

volumes:
  mongo-data:
